source 'https://rubygems.org'
ruby '2.4.1'

gem 'devise'
gem 'figaro'
gem 'jbuilder', '~> 2.0'
gem 'pg'
gem 'puma'
gem 'rails', '5.0.5'
gem 'redis'

gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem "font-awesome-rails"
gem 'friendly_id', '~> 5.2.0'
gem 'jquery-rails'
gem 'postmark-rails'
gem 'remotipart', github: 'mshibuya/remotipart'
gem 'rails_admin', '~> 1.3'
gem 'sass-rails'
gem 'simple_form'
gem 'stripe'
gem 'uk_postcode', '~> 2.1.0'
gem 'uglifier'
gem 'carrierwave', '~> 1.0'
gem 'cloudinary'
gem 'instagram_api_client'

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'dotenv-rails'
  gem 'letter_opener'
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
