# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Group.find_or_create_by(name: 'A')
Group.find_or_create_by(name: 'B')
Group.find_or_create_by(name: 'C')

Size.find_or_create_by(name: , kcal: 200)
Size.find_or_create_by(name: , kcal: 325)
Size.find_or_create_by(name: , kcal: 450)
Size.find_or_create_by(name: , kcal: 575)
Size.find_or_create_by(name: , kcal: 700)

Shake.create(name: 'Shake A' ,group_id: Group.find_by(name: 'A').id, size_id: 1)
Shake.create(name: 'Shake B' ,group_id: Group.find_by(name: 'A').id, size_id: 2)
Shake.create(name: 'Shake C' ,group_id: Group.find_by(name: 'A').id, size_id: 3)
Shake.create(name: 'Shake D' ,group_id: Group.find_by(name: 'A').id, size_id: 4)
Shake.create(name: 'Shake E' ,group_id: Group.find_by(name: 'A').id, size_id: 5)

Shake.create(name: 'Shake F' ,group_id: Group.find_by(name: 'B').id, size_id: 1)
Shake.create(name: 'Shake G' ,group_id: Group.find_by(name: 'B').id, size_id: 2)
Shake.create(name: 'Shake H' ,group_id: Group.find_by(name: 'B').id, size_id: 3)
Shake.create(name: 'Shake I' ,group_id: Group.find_by(name: 'B').id, size_id: 4)
Shake.create(name: 'Shake J' ,group_id: Group.find_by(name: 'B').id, size_id: 5)

Shake.create(name: 'Shake K' ,group_id: Group.find_by(name: 'C').id, size_id: 1)
Shake.create(name: 'Shake L' ,group_id: Group.find_by(name: 'C').id, size_id: 2)
Shake.create(name: 'Shake M' ,group_id: Group.find_by(name: 'C').id, size_id: 3)
Shake.create(name: 'Shake N' ,group_id: Group.find_by(name: 'C').id, size_id: 4)
Shake.create(name: 'Shake P' ,group_id: Group.find_by(name: 'C').id, size_id: 5)

NutritionalInfo.find_or_create_by(shake_id:)
NutritionalInfo.find_or_create_by(shake_id:)
NutritionalInfo.find_or_create_by(shake_id:)
NutritionalInfo.find_or_create_by(shake_id:)
NutritionalInfo.find_or_create_by(shake_id:)
NutritionalInfo.find_or_create_by(shake_id:)
NutritionalInfo.find_or_create_by(shake_id:)
NutritionalInfo.find_or_create_by(shake_id:)
NutritionalInfo.find_or_create_by(shake_id:)
NutritionalInfo.find_or_create_by(shake_id:)
NutritionalInfo.find_or_create_by(shake_id:)
NutritionalInfo.find_or_create_by(shake_id:)
NutritionalInfo.find_or_create_by(shake_id:)
NutritionalInfo.find_or_create_by(shake_id:)
NutritionalInfo.find_or_create_by(shake_id:)

Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)
Ingredient.find_or_create_by(name:)

ShakeIngredients.find_or_create_by(shake_id:, ingredient_id:)
ShakeIngredients.find_or_create_by(shake_id:, ingredient_id:)
ShakeIngredients.find_or_create_by(shake_id:, ingredient_id:)
ShakeIngredients.find_or_create_by(shake_id:, ingredient_id:)
ShakeIngredients.find_or_create_by(shake_id:, ingredient_id:)
