# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Group.find_or_create_by(name: 'A')
Group.find_or_create_by(name: 'B')
Group.find_or_create_by(name: 'C')

Size.find_or_create_by(name: , kcal: 200)
Size.find_or_create_by(name: , kcal: 325)
Size.find_or_create_by(name: , kcal: 450)
Size.find_or_create_by(name: , kcal: 575)
Size.find_or_create_by(name: , kcal: 700)

Shake.all.destroy_all

Shake.create(name: 'Apple Crumble' ,group_id: Group.find_by(name: 'A').id, size_id: Size.find_by(kcal: 200).id)
Shake.create(name: 'Blueberry' ,group_id: Group.find_by(name: 'A').id, size_id: Size.find_by(kcal: 325).id)
Shake.create(name: 'Choc & Nut' ,group_id: Group.find_by(name: 'A').id, size_id: Size.find_by(kcal: 450).id)
Shake.create(name: 'Tropical Fruit' ,group_id: Group.find_by(name: 'A').id, size_id: Size.find_by(kcal: 575).id)
Shake.create(name: 'Pomegranate & Banana' ,group_id: Group.find_by(name: 'A').id, size_id: Size.find_by(kcal: 700).id)

Shake.create(name: 'Pear & Cashew' ,group_id: Group.find_by(name: 'B').id, size_id: Size.find_by(kcal: 200).id)
Shake.create(name: 'Peach' ,group_id: Group.find_by(name: 'B').id, size_id: Size.find_by(kcal: 325).id)
Shake.create(name: 'Cherry' ,group_id: Group.find_by(name: 'B').id, size_id: Size.find_by(kcal: 450).id)
Shake.create(name: 'Lemon & Lime' ,group_id: Group.find_by(name: 'B').id, size_id: Size.find_by(kcal: 575).id)
Shake.create(name: 'Raspberry' ,group_id: Group.find_by(name: 'B').id, size_id: Size.find_by(kcal: 700).id)

Shake.create(name: 'Espresso Martini' ,group_id: Group.find_by(name: 'C').id, size_id: Size.find_by(kcal: 200).id)
Shake.create(name: 'Vanilla & Strawberry' ,group_id: Group.find_by(name: 'C').id, size_id: Size.find_by(kcal: 325).id)
Shake.create(name: 'Grape' ,group_id: Group.find_by(name: 'C').id, size_id: Size.find_by(kcal: 450).id)
Shake.create(name: 'Apple & Cinnamon' ,group_id: Group.find_by(name: 'C').id, size_id: Size.find_by(kcal: 575).id)
Shake.create(name: 'Cacao & Vanilla' ,group_id: Group.find_by(name: 'C').id, size_id: Size.find_by(kcal: 700).id)

# NutritionalInfo.find_or_create_by(shake_id:)
# NutritionalInfo.find_or_create_by(shake_id:)
# NutritionalInfo.find_or_create_by(shake_id:)
# NutritionalInfo.find_or_create_by(shake_id:)
# NutritionalInfo.find_or_create_by(shake_id:)
# NutritionalInfo.find_or_create_by(shake_id:)
# NutritionalInfo.find_or_create_by(shake_id:)
# NutritionalInfo.find_or_create_by(shake_id:)
# NutritionalInfo.find_or_create_by(shake_id:)
# NutritionalInfo.find_or_create_by(shake_id:)
# NutritionalInfo.find_or_create_by(shake_id:)
# NutritionalInfo.find_or_create_by(shake_id:)
# NutritionalInfo.find_or_create_by(shake_id:)
# NutritionalInfo.find_or_create_by(shake_id:)
# NutritionalInfo.find_or_create_by(shake_id:)

# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)

# ShakeIngredient.find_or_create_by(shake_id:, ingredient_id:)
# ShakeIngredient.find_or_create_by(shake_id:, ingredient_id:)
# ShakeIngredient.find_or_create_by(shake_id:, ingredient_id:)
# ShakeIngredient.find_or_create_by(shake_id:, ingredient_id:)
# ShakeIngredient.find_or_create_by(shake_id:, ingredient_id:)
