# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Group.find_or_create_by(name: 'A', protein:)
Group.find_or_create_by(name: 'B', protein:)
Group.find_or_create_by(name: 'C', protein:)

Size.find_or_create_by(name: 'i', kcal: 200)
Size.find_or_create_by(name: 'ii', kcal: 325)
Size.find_or_create_by(name: 'iii', kcal: 450)
Size.find_or_create_by(name: 'iv', kcal: 575)
Size.find_or_create_by(name: 'v', kcal: 700)

# Smoothie.all.destroy_all

# Smoothie.create(name: 'Apple Crumble' ,group_id: Group.find_by(name: 'A').id, size_id: Size.find_by(kcal: 200).id)
# Smoothie.create(name: 'Blueberry' ,group_id: Group.find_by(name: 'A').id, size_id: Size.find_by(kcal: 325).id)
# Smoothie.create(name: 'Choc & Nut' ,group_id: Group.find_by(name: 'A').id, size_id: Size.find_by(kcal: 450).id)
# Smoothie.create(name: 'Tropical Fruit' ,group_id: Group.find_by(name: 'A').id, size_id: Size.find_by(kcal: 575).id)
# Smoothie.create(name: 'Pomegranate & Banana' ,group_id: Group.find_by(name: 'A').id, size_id: Size.find_by(kcal: 700).id)

# Smoothie.create(name: 'Pear & Cashew' ,group_id: Group.find_by(name: 'B').id, size_id: Size.find_by(kcal: 200).id)
# Smoothie.create(name: 'Peach' ,group_id: Group.find_by(name: 'B').id, size_id: Size.find_by(kcal: 325).id)
# Smoothie.create(name: 'Cherry' ,group_id: Group.find_by(name: 'B').id, size_id: Size.find_by(kcal: 450).id)
# Smoothie.create(name: 'Lemon & Lime' ,group_id: Group.find_by(name: 'B').id, size_id: Size.find_by(kcal: 575).id)
# Smoothie.create(name: 'Raspberry' ,group_id: Group.find_by(name: 'B').id, size_id: Size.find_by(kcal: 700).id)

# Smoothie.create(name: 'Espresso Martini' ,group_id: Group.find_by(name: 'C').id, size_id: Size.find_by(kcal: 200).id)
# Smoothie.create(name: 'Vanilla & Strawberry' ,group_id: Group.find_by(name: 'C').id, size_id: Size.find_by(kcal: 325).id)
# Smoothie.create(name: 'Grape' ,group_id: Group.find_by(name: 'C').id, size_id: Size.find_by(kcal: 450).id)
# Smoothie.create(name: 'Apple & Cinnamon' ,group_id: Group.find_by(name: 'C').id, size_id: Size.find_by(kcal: 575).id)
# Smoothie.create(name: 'Cacao & Vanilla' ,group_id: Group.find_by(name: 'C').id, size_id: Size.find_by(kcal: 700).id)

# NutritionalInfo.find_or_create_by(smoothie_id:)
# NutritionalInfo.find_or_create_by(smoothie_id:)
# NutritionalInfo.find_or_create_by(smoothie_id:)
# NutritionalInfo.find_or_create_by(smoothie_id:)
# NutritionalInfo.find_or_create_by(smoothie_id:)
# NutritionalInfo.find_or_create_by(smoothie_id:)
# NutritionalInfo.find_or_create_by(smoothie_id:)
# NutritionalInfo.find_or_create_by(smoothie_id:)
# NutritionalInfo.find_or_create_by(smoothie_id:)
# NutritionalInfo.find_or_create_by(smoothie_id:)
# NutritionalInfo.find_or_create_by(smoothie_id:)
# NutritionalInfo.find_or_create_by(smoothie_id:)
# NutritionalInfo.find_or_create_by(smoothie_id:)
# NutritionalInfo.find_or_create_by(smoothie_id:)
# NutritionalInfo.find_or_create_by(smoothie_id:)

# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)
# Ingredient.find_or_create_by(name:)

# SmoothieIngredient.find_or_create_by(smoothie_id:, ingredient_id:)
# SmoothieIngredient.find_or_create_by(smoothie_id:, ingredient_id:)
# SmoothieIngredient.find_or_create_by(smoothie_id:, ingredient_id:)
# SmoothieIngredient.find_or_create_by(smoothie_id:, ingredient_id:)
# SmoothieIngredient.find_or_create_by(smoothie_id:, ingredient_id:)
